<?php
// AI-CMS V2.0 权限配置（简化RBAC，role_id字段控制）

return [
    // 角色定义
    'roles' => [
        1 => ['name' => '超级管理员', 'permissions' => '*'],
        2 => ['name' => '管理员', 'permissions' => ['content.*', 'cate.*', 'tag.*', 'user.*', 'system.*', 'media.*', 'banner.*', 'link.*', 'review.*', 'comment.*', 'member.*', 'member_level.*', 'points.*', 'points_product.*', 'points_exchange.*', 'seo.*', 'seo_keyword.*', 'export.*', 'token.*', 'ad.*', 'notification.*', 'log.*', 'ai_model.*', 'ai_log.*', 'paid_order.*', 'dashboard.*', 'form.*', 'import.*', 'email_subscriber.*', 'visit_archive.*', 'payment.*', 'ai_batch.*', 'collect.*', 'publish.*', 'email.*', 'plugin.*', 'language.*', 'theme_market.*', 'captcha.*', 'ai_template.*']],
        3 => ['name' => '编辑', 'permissions' => ['content.*', 'cate.list', 'tag.list', 'media.list', 'media.upload']],
    ],
    
    // 权限映射（permission key => 控制器方法映射）
    'map' => [
        'content.*' => ['admin/content/index', 'admin/content/add', 'admin/content/edit', 'admin/content/delete', 'admin/content/recycleBin', 'admin/content/restore', 'admin/content/forceDelete'],
        'content.list' => ['admin/content/index'],
        'content.add' => ['admin/content/add'],
        'content.edit' => ['admin/content/edit'],
        'content.delete' => ['admin/content/delete'],
        'content.recycle' => ['admin/content/recycleBin', 'admin/content/restore', 'admin/content/forceDelete'],
        'cate.*' => ['admin/cate/index', 'admin/cate/add', 'admin/cate/edit', 'admin/cate/delete'],
        'cate.list' => ['admin/cate/index'],
        'tag.*' => ['admin/tag/index', 'admin/tag/add', 'admin/tag/edit', 'admin/tag/delete'],
        'tag.list' => ['admin/tag/index'],
        'user.*' => ['admin/user/index', 'admin/user/add', 'admin/user/edit', 'admin/user/delete'],
        'system.*' => ['admin/system/config', 'admin/system/customVar', 'admin/system/moduleControl', 'admin/log/index', 'admin/system/templates', 'admin/system/setTheme', 'admin/system/adminTemplates', 'admin/system/setAdminTheme', 'admin/system/allTemplates'],
        'system.templates' => ['admin/system/templates', 'admin/system/setTheme', 'admin/system/allTemplates'],
        'system.adminTheme' => ['admin/system/adminTemplates', 'admin/system/setAdminTheme'],
        'system.log' => ['admin/log/index'],
        'system.customVar' => ['admin/system/customVar', 'admin/system/customVarSave', 'admin/system/customVarDelete'],
        'system.moduleControl' => ['admin/system/moduleControl', 'admin/system/moduleToggle'],
        'media.*' => ['admin/media/index', 'admin/media/upload', 'admin/media/edit', 'admin/media/delete', 'admin/media/select'],
        'media.list' => ['admin/media/index', 'admin/media/select'],
        'media.upload' => ['admin/media/upload'],
        'banner.*' => ['admin/banner/index', 'admin/banner/add', 'admin/banner/edit', 'admin/banner/delete'],
        'review.*' => ['admin/review/index', 'admin/review/approve', 'admin/review/reject', 'admin/review/history'],
        'backup.*' => ['admin/backup/index', 'admin/backup/create', 'admin/backup/restore', 'admin/backup/delete', 'admin/backup/download'],
        'comment.*' => ['admin/comment/index', 'admin/comment/audit', 'admin/comment/delete', 'admin/comment/batch'],
        'member.*' => ['admin/member/index', 'admin/member/detail', 'admin/member/add', 'admin/member/edit', 'admin/member/delete', 'admin/member/toggleStatus', 'admin/member/audit'],
        'seo.*' => ['admin/seo/index', 'admin/seo/sitemap', 'admin/seo/robots'],
        'export.*' => ['admin/export/index'],
        'token.*' => ['admin/token/index', 'admin/token/create', 'admin/token/revoke'],
        'ad.*' => ['admin/ad/index', 'admin/ad/add', 'admin/ad/edit', 'admin/ad/delete', 'admin/ad/stat', 'admin/ad_position/index', 'admin/ad_position/add', 'admin/ad_position/edit', 'admin/ad_position/delete'],
        'link.*' => ['admin/link/index', 'admin/link/add', 'admin/link/edit', 'admin/link/delete', 'admin/link_group/index', 'admin/link_group/add', 'admin/link_group/edit', 'admin/link_group/delete', 'admin/link_group/toggleStatus'],
        'notification.*' => ['admin/notification/index', 'admin/notification/read'],
        'log.*' => ['admin/log/index', 'admin/log/export', 'admin/log/cleanup'],
        'member_level.*' => ['admin/member_level/index', 'admin/member_level/add', 'admin/member_level/edit', 'admin/member_level/delete'],
        'points.*' => ['admin/points_rule/index', 'admin/points_rule/save'],
        'ai_model.*' => ['admin/ai_model/index', 'admin/ai_model/add', 'admin/ai_model/edit', 'admin/ai_model/delete', 'admin/ai_model/setDefault', 'admin/ai_model/testConnection'],
        'ai_log.*' => ['admin/ai_log/index', 'admin/ai_log/detail', 'admin/ai_log/cleanup'],
        'paid_order.*' => ['admin/paid_order/index', 'admin/paid_order/detail', 'admin/paid_order/refund'],
        'dashboard.*' => ['admin/dashboard/index', 'admin/dashboard/overview', 'admin/dashboard/trend', 'admin/dashboard/topContent', 'admin/dashboard/categoryStats'],
        'form.*' => ['admin/form/index', 'admin/form/add', 'admin/form/edit', 'admin/form/editor', 'admin/form/save', 'admin/form/delete', 'admin/form/dataIndex', 'admin/form/dataDetail', 'admin/form/dataExport', 'admin/form/dataDelete', 'admin/form/toggleEnabled'],
        'seo_keyword.*' => ['admin/seo_keyword/index', 'admin/seo_keyword/add', 'admin/seo_keyword/edit', 'admin/seo_keyword/delete', 'admin/seo_keyword/import', 'admin/seo_keyword/group', 'admin/seo_keyword/saveGroup', 'admin/seo_keyword/deleteGroup'],
        'import.*' => ['admin/import/index', 'admin/import/import'],
        'email_subscriber.*' => ['admin/email_subscriber/index', 'admin/email_subscriber/delete', 'admin/email_subscriber/export'],
        'visit_archive.*' => ['admin/visit_archive/index', 'admin/visit_archive/execute', 'admin/visit_archive/detail'],
        // V2.5 新增权限映射
        'payment.*' => ['admin/payment/index', 'admin/payment/config', 'admin/payment/refund', 'admin/payment/revenue'],
        'payment.config' => ['admin/payment/config'],
        'payment.refund' => ['admin/payment/refund'],
        'payment.revenue' => ['admin/payment/revenue'],
        'ai_batch.*' => ['admin/ai_batch/index', 'admin/ai_batch/create', 'admin/ai_batch/detail', 'admin/ai_batch/cancel'],
        'collect.*' => ['admin/collect_source/index', 'admin/collect_source/add', 'admin/collect_source/edit', 'admin/collect_source/delete', 'admin/collect_source/run', 'admin/collect_log/index', 'admin/collect_log/detail'],
        'collect.source' => ['admin/collect_source/index', 'admin/collect_source/add', 'admin/collect_source/edit', 'admin/collect_source/delete', 'admin/collect_source/run'],
        'collect.log' => ['admin/collect_log/index', 'admin/collect_log/detail'],
        'publish.*' => ['admin/publish_platform/index', 'admin/publish_platform/add', 'admin/publish_platform/edit', 'admin/publish_platform/delete', 'admin/publish_log/index', 'admin/publish_log/publish'],
        'publish.platform' => ['admin/publish_platform/index', 'admin/publish_platform/add', 'admin/publish_platform/edit', 'admin/publish_platform/delete'],
        'publish.log' => ['admin/publish_log/index', 'admin/publish_log/publish'],
        'email.*' => ['admin/email_template/index', 'admin/email_template/add', 'admin/email_template/edit', 'admin/email_template/delete', 'admin/email_template/test', 'admin/email_log/index'],
        'email.template' => ['admin/email_template/index', 'admin/email_template/add', 'admin/email_template/edit', 'admin/email_template/delete', 'admin/email_template/test'],
        'email.log' => ['admin/email_log/index'],
        'plugin.*' => ['admin/plugin/index', 'admin/plugin/install', 'admin/plugin/uninstall', 'admin/plugin/enable', 'admin/plugin/disable', 'admin/plugin/config'],
        'language.*' => ['admin/language/index', 'admin/language/add', 'admin/language/edit', 'admin/language/delete', 'admin/language/translate'],
        'theme_market.*' => ['admin/theme_market/index', 'admin/theme_market/scan', 'admin/theme_market/install', 'admin/theme_market/uninstall', 'admin/theme_market/checkUpdate'],
        'captcha.*' => ['admin/captcha/config'],
        // V2.6 新增权限映射
        'storage.*' => ['admin/storage/config', 'admin/storage/saveConfig'],
        'chapter.*' => ['admin/chapter/index', 'admin/chapter/add', 'admin/chapter/edit', 'admin/chapter/delete', 'admin/chapter/sort'],
        'message.*' => ['admin/message/system', 'admin/message/sendSystem'],
        'workflow.*' => ['admin/workflow/index', 'admin/workflow/add', 'admin/workflow/edit', 'admin/workflow/delete', 'admin/workflow/records'],
        'oauth.*' => ['admin/oauth_config/index', 'admin/oauth_config/save'],
        'points_product.*' => ['admin/points_product/index', 'admin/points_product/add', 'admin/points_product/edit', 'admin/points_product/delete'],
        'points_exchange.*' => ['admin/points_exchange/index', 'admin/points_exchange/audit', 'admin/points_exchange/detail'],
        'ai_template.*' => ['admin/ai_template/index', 'admin/ai_template/edit', 'admin/ai_template/delete', 'admin/ai_template/use', 'admin/ai_template/progress'],
    ],
];
